// <auto-generated />
using System;
using BranallyGames.Wism.Repository.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BranallyGames.Wism.Repository.Migrations
{
    [DbContext(typeof(WismDbContext))]
    [Migration("20200914005110_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BranallyGames.Wism.Repository.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Worlds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("517fed59-d8dc-4b59-b6ca-2052f75aabf7"),
                            DisplayName = "Etheria",
                            ShortName = "Etheria"
                        },
                        new
                        {
                            Id = new Guid("b0113c1c-4ee8-421d-82ce-1b65207c9017"),
                            DisplayName = "Britannia",
                            ShortName = "Britannia"
                        },
                        new
                        {
                            Id = new Guid("ee082e96-71da-453b-9252-17c8b4f3be65"),
                            DisplayName = "United States of America",
                            ShortName = "USA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
