// <auto-generated />
using System;
using BranallyGames.Wism.Repository.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BranallyGames.Wism.Repository.Migrations
{
    [DbContext(typeof(WismDbContext))]
    [Migration("20200917010545_playersadded")]
    partial class playersadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BranallyGames.Wism.Repository.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<bool>("IsHuman")
                        .HasColumnType("bit");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("986c478b-6554-4a2c-805f-dc059632b707"),
                            DisplayName = "Branally",
                            IsHuman = false,
                            ShortName = "Brian",
                            WorldId = new Guid("517fed59-d8dc-4b59-b6ca-2052f75aabf7")
                        },
                        new
                        {
                            Id = new Guid("3def6dbb-fa0c-4010-a73f-aad13b50697b"),
                            DisplayName = "Danally",
                            IsHuman = false,
                            ShortName = "Dan",
                            WorldId = new Guid("517fed59-d8dc-4b59-b6ca-2052f75aabf7")
                        },
                        new
                        {
                            Id = new Guid("a0466732-e79e-4789-b883-7b43506795e3"),
                            DisplayName = "Branally",
                            IsHuman = false,
                            ShortName = "Brian",
                            WorldId = new Guid("b0113c1c-4ee8-421d-82ce-1b65207c9017")
                        },
                        new
                        {
                            Id = new Guid("1b9991bf-e454-486a-8f5c-297dd69fe60c"),
                            DisplayName = "Jake the Snake",
                            IsHuman = false,
                            ShortName = "Jacob",
                            WorldId = new Guid("b0113c1c-4ee8-421d-82ce-1b65207c9017")
                        },
                        new
                        {
                            Id = new Guid("b07173b3-290b-4490-bf9a-d3588a251854"),
                            DisplayName = "Branally",
                            IsHuman = false,
                            ShortName = "Brian",
                            WorldId = new Guid("ee082e96-71da-453b-9252-17c8b4f3be65")
                        },
                        new
                        {
                            Id = new Guid("3ef6ba4b-3f46-46a5-8705-2a1ea045a381"),
                            DisplayName = "Owen Little",
                            IsHuman = false,
                            ShortName = "Owen",
                            WorldId = new Guid("ee082e96-71da-453b-9252-17c8b4f3be65")
                        });
                });

            modelBuilder.Entity("BranallyGames.Wism.Repository.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Worlds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("517fed59-d8dc-4b59-b6ca-2052f75aabf7"),
                            DisplayName = "Etheria",
                            ShortName = "Etheria"
                        },
                        new
                        {
                            Id = new Guid("b0113c1c-4ee8-421d-82ce-1b65207c9017"),
                            DisplayName = "Britannia",
                            ShortName = "Britannia"
                        },
                        new
                        {
                            Id = new Guid("ee082e96-71da-453b-9252-17c8b4f3be65"),
                            DisplayName = "United States of America",
                            ShortName = "USA"
                        });
                });

            modelBuilder.Entity("BranallyGames.Wism.Repository.Entities.Player", b =>
                {
                    b.HasOne("BranallyGames.Wism.Repository.Entities.World", "World")
                        .WithMany("Players")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
