<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>wism</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wism.Client.AI\Wism.Client.AI.csproj" />
    <ProjectReference Include="..\Wism.Client.Api\Wism.Client.Api.csproj" />
    <ProjectReference Include="..\Wism.Client.Core\Wism.Client.Core.csproj" />
    <ProjectReference Include="..\Wism.Companion.Shared\Wism.Companion.Shared.csproj" />
  </ItemGroup>

</Project>
