// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wism.Client.Data.DbContexts;

namespace Wism.Client.Data.Migrations
{
    [DbContext(typeof(WismClientDbContext))]
    partial class WismClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wism.Client.Data.Entities.Army", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Armies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5771f514-edce-463b-9f54-d0bb30adeb57"),
                            HitPoints = 2,
                            Name = "Hero",
                            Strength = 5,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = new Guid("ddc9272a-f93d-4bd2-9351-7877b40feada"),
                            HitPoints = 2,
                            Name = "Light Infantry",
                            Strength = 3,
                            X = 0,
                            Y = 5
                        });
                });

            modelBuilder.Entity("Wism.Client.Data.Entities.ArmyCommand", b =>
                {
                    b.Property<Guid>("ArmyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommandId")
                        .HasColumnType("int");

                    b.HasKey("ArmyId", "CommandId");

                    b.HasIndex("CommandId");

                    b.ToTable("ArmyCommand");
                });

            modelBuilder.Entity("Wism.Client.Data.Entities.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Commands");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Command");
                });

            modelBuilder.Entity("Wism.Client.Data.Entities.AttackCommand", b =>
                {
                    b.HasBaseType("Wism.Client.Data.Entities.Command");

                    b.HasDiscriminator().HasValue("AttackCommand");
                });

            modelBuilder.Entity("Wism.Client.Data.Entities.MoveCommand", b =>
                {
                    b.HasBaseType("Wism.Client.Data.Entities.Command");

                    b.HasDiscriminator().HasValue("MoveCommand");
                });

            modelBuilder.Entity("Wism.Client.Data.Entities.ArmyCommand", b =>
                {
                    b.HasOne("Wism.Client.Data.Entities.Army", "Army")
                        .WithMany("ArmyCommands")
                        .HasForeignKey("ArmyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wism.Client.Data.Entities.Command", "Command")
                        .WithMany("ArmyCommands")
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
