name: WISM CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - wism_dev

jobs:
  build-and-test-client:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Build WismClient
      run: dotnet build WismClient/WismClient.sln --configuration Release

    - name: Test WismClient
      run: dotnet test WismClient/WismClient.sln --configuration Release
